services:
  - type: web
    name: xtin-trade
    env: static
    plan: free
    repo: "https://github.com/ChetanO07/Xtin-CryptoExchange"
    branch: main
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
